# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * 0' # https://crontab.guru/

name: Build it

jobs:
  Build:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.2.2
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write  
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      # Installing quarto
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 0.3.71
    
      - name: Install packags and render
        run: |
          install2.r xml2 quarto
          quarto render README.qmd
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'README.*'
          commit_message: Updated README (auto)
          
